============================= test session starts ==============================
platform linux -- Python 3.10.14, pytest-8.3.1, pluggy-1.5.0 -- /home/arazthexd/miniforge3/envs/sqmvscreen2/bin/python3.10
cachedir: .pytest_cache
rootdir: /home/arazthexd/projects/002_sqm
plugins: typeguard-4.3.0, anyio-4.4.0, time-machine-2.14.2
collecting ... collected 4 items

tests/modules/mopac/test_mopac_opt.py::test_mopac_lig_opt[lig_opter0] Executing with input: {'ligands': <molsberry.core.data.collections.BatchedData object at 0x7fce94439240>}
Unwrapping input: {}
Apply on batch: {'ligands': <molsberry.core.data.collections.BatchedData object at 0x7fce94439240>}


=============================== warnings summary ===============================
tests/modules/mopac/test_mopac_opt.py::test_mopac_lig_opt[lig_opter0]
  /home/arazthexd/miniforge3/envs/sqmvscreen2/lib/python3.10/site-packages/mpire/pool.py:693: RuntimeWarning: Failed to obtain length of iterable when chunk size or number of splits is None. Chunk size is set to 4. Remedy: either provide an iterable with a len() function or specify iterable_len in the function call
    n_tasks, max_tasks_active, chunk_size, progress_bar, progress_bar_options = check_map_parameters(

tests/modules/mopac/test_mopac_opt.py::test_mopac_lig_opt[lig_opter0]
  /home/arazthexd/miniforge3/envs/sqmvscreen2/lib/python3.10/site-packages/_pytest/threadexception.py:82: PytestUnhandledThreadExceptionWarning: Exception in thread Thread-7 (_terminate_worker)
  
  Traceback (most recent call last):
    File "/home/arazthexd/miniforge3/envs/sqmvscreen2/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
      self.run()
    File "/home/arazthexd/miniforge3/envs/sqmvscreen2/lib/python3.10/threading.py", line 953, in run
      self._target(*self._args, **self._kwargs)
    File "/home/arazthexd/miniforge3/envs/sqmvscreen2/lib/python3.10/site-packages/mpire/pool.py", line 1055, in _terminate_worker
      if self._workers[worker_id] is None or self._workers[worker_id].pid is None:
    File "/home/arazthexd/miniforge3/envs/sqmvscreen2/lib/python3.10/multiprocessing/process.py", line 239, in ident
      self._check_closed()
    File "/home/arazthexd/miniforge3/envs/sqmvscreen2/lib/python3.10/multiprocessing/process.py", line 101, in _check_closed
      raise ValueError("process object is closed")
  ValueError: process object is closed
  
    warnings.warn(pytest.PytestUnhandledThreadExceptionWarning(msg))

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
============================== slowest durations ===============================
0.02s setup    tests/modules/mopac/test_mopac_opt.py::test_mopac_lig_opt[lig_opter0]
============================= 2 warnings in 20.67s =============================
